# ATTENTION: no deployment should be done until serverless.yml is properly setup
name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.yml'
      - 'request-amz-stock-update.js'
      - 'layer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Install layer dependencies
      run: |
        cd layer/nodejs
        npm i
    - name: serverless-check
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy --noDeploy'
        should_throw: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SELLER_ID: ${{ secrets.SELLER_ID }}
        MWS_AUTH_TOKEN: ${{ secrets.MWS_AUTH_TOKEN }}
    - name: serverless-deploy
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy -v'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SELLER_ID: ${{ secrets.SELLER_ID }}
        MWS_AUTH_TOKEN: ${{ secrets.MWS_AUTH_TOKEN }}
